"""tablas iniciales

Revision ID: 7a3bc26f4e3f
Revises: 
Create Date: 2026-05-21 14:47:59.772068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a3bc26f4e3f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('id_categoria', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_categoria')
    )
    op.create_index(op.f('ix_categoria_id_categoria'), 'categoria', ['id_categoria'], unique=False)
    op.create_table('condicion',
    sa.Column('id_condicion', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_condicion')
    )
    op.create_index(op.f('ix_condicion_id_condicion'), 'condicion', ['id_condicion'], unique=False)
    op.create_table('status_pago',
    sa.Column('id_status', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_status')
    )
    op.create_index(op.f('ix_status_pago_id_status'), 'status_pago', ['id_status'], unique=False)
    op.create_table('status_producto',
    sa.Column('id_status', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_status')
    )
    op.create_index(op.f('ix_status_producto_id_status'), 'status_producto', ['id_status'], unique=False)
    op.create_table('status_subasta',
    sa.Column('id_status', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_status')
    )
    op.create_index(op.f('ix_status_subasta_id_status'), 'status_subasta', ['id_status'], unique=False)
    op.create_table('tipo_notificacion',
    sa.Column('id_tipo_notificacion', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_tipo_notificacion')
    )
    op.create_index(op.f('ix_tipo_notificacion_id_tipo_notificacion'), 'tipo_notificacion', ['id_tipo_notificacion'], unique=False)
    op.create_table('tipo_subasta',
    sa.Column('id_tipo_subasta', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_tipo_subasta')
    )
    op.create_index(op.f('ix_tipo_subasta_id_tipo_subasta'), 'tipo_subasta', ['id_tipo_subasta'], unique=False)
    op.create_table('tipo_usuario',
    sa.Column('id_tipo_usuario', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_tipo_usuario')
    )
    op.create_index(op.f('ix_tipo_usuario_id_tipo_usuario'), 'tipo_usuario', ['id_tipo_usuario'], unique=False)
    op.create_table('usuario',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('correo', sa.String(length=150), nullable=False),
    sa.Column('contrasena', sa.String(length=255), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido_paterno', sa.String(length=100), nullable=False),
    sa.Column('apellido_materno', sa.String(length=100), nullable=True),
    sa.Column('calificacion', sa.Float(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('suspendido', sa.Boolean(), nullable=True),
    sa.Column('fecha_suspension', sa.DateTime(), nullable=True),
    sa.Column('cve_tipo_usuario', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cve_tipo_usuario'], ['tipo_usuario.id_tipo_usuario'], ),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    op.create_index(op.f('ix_usuario_correo'), 'usuario', ['correo'], unique=True)
    op.create_index(op.f('ix_usuario_id_usuario'), 'usuario', ['id_usuario'], unique=False)
    op.create_table('metodo_envio',
    sa.Column('id_metodo_envio', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=150), nullable=False),
    sa.Column('cve_usuario', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cve_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_metodo_envio')
    )
    op.create_index(op.f('ix_metodo_envio_id_metodo_envio'), 'metodo_envio', ['id_metodo_envio'], unique=False)
    op.create_table('producto',
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('ubicacion', sa.String(length=200), nullable=True),
    sa.Column('cve_categoria', sa.Integer(), nullable=True),
    sa.Column('cve_condicion', sa.Integer(), nullable=True),
    sa.Column('cve_usuario', sa.Integer(), nullable=True),
    sa.Column('cve_status', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cve_categoria'], ['categoria.id_categoria'], ),
    sa.ForeignKeyConstraint(['cve_condicion'], ['condicion.id_condicion'], ),
    sa.ForeignKeyConstraint(['cve_status'], ['status_producto.id_status'], ),
    sa.ForeignKeyConstraint(['cve_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_producto')
    )
    op.create_index(op.f('ix_producto_id_producto'), 'producto', ['id_producto'], unique=False)
    op.create_table('foto_producto',
    sa.Column('id_foto', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('cve_producto', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cve_producto'], ['producto.id_producto'], ),
    sa.PrimaryKeyConstraint('id_foto')
    )
    op.create_index(op.f('ix_foto_producto_id_foto'), 'foto_producto', ['id_foto'], unique=False)
    op.create_table('inmueble',
    sa.Column('id_inmueble', sa.Integer(), nullable=False),
    sa.Column('tipo_propiedad', sa.String(length=100), nullable=True),
    sa.Column('superficie_terreno', sa.Float(), nullable=True),
    sa.Column('superficie_construida', sa.Float(), nullable=True),
    sa.Column('no_habitaciones', sa.Integer(), nullable=True),
    sa.Column('ubicacion_detallada', sa.Text(), nullable=True),
    sa.Column('url_documentacion', sa.String(length=500), nullable=True),
    sa.Column('cve_producto', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cve_producto'], ['producto.id_producto'], ),
    sa.PrimaryKeyConstraint('id_inmueble'),
    sa.UniqueConstraint('cve_producto')
    )
    op.create_index(op.f('ix_inmueble_id_inmueble'), 'inmueble', ['id_inmueble'], unique=False)
    op.create_table('subasta',
    sa.Column('id_subasta', sa.Integer(), nullable=False),
    sa.Column('precio_inicial', sa.Float(), nullable=False),
    sa.Column('precio_actual', sa.Float(), nullable=False),
    sa.Column('incremento', sa.Float(), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=False),
    sa.Column('fecha_final', sa.DateTime(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.Column('cve_tipo_subasta', sa.Integer(), nullable=True),
    sa.Column('cve_producto', sa.Integer(), nullable=True),
    sa.Column('cve_status', sa.Integer(), nullable=True),
    sa.Column('cve_usuario_ganador', sa.Integer(), nullable=True),
    sa.Column('cve_segundo_postor', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cve_producto'], ['producto.id_producto'], ),
    sa.ForeignKeyConstraint(['cve_segundo_postor'], ['usuario.id_usuario'], ),
    sa.ForeignKeyConstraint(['cve_status'], ['status_subasta.id_status'], ),
    sa.ForeignKeyConstraint(['cve_tipo_subasta'], ['tipo_subasta.id_tipo_subasta'], ),
    sa.ForeignKeyConstraint(['cve_usuario_ganador'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_subasta')
    )
    op.create_index(op.f('ix_subasta_id_subasta'), 'subasta', ['id_subasta'], unique=False)
    op.create_table('vehiculo',
    sa.Column('id_vehiculo', sa.Integer(), nullable=False),
    sa.Column('marca', sa.String(length=100), nullable=False),
    sa.Column('modelo', sa.String(length=100), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('kilometraje', sa.Float(), nullable=True),
    sa.Column('numero_serie', sa.String(length=100), nullable=True),
    sa.Column('condicion_mecanica', sa.Text(), nullable=True),
    sa.Column('url_documentacion', sa.String(length=500), nullable=True),
    sa.Column('cve_producto', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cve_producto'], ['producto.id_producto'], ),
    sa.PrimaryKeyConstraint('id_vehiculo'),
    sa.UniqueConstraint('cve_producto')
    )
    op.create_index(op.f('ix_vehiculo_id_vehiculo'), 'vehiculo', ['id_vehiculo'], unique=False)
    op.create_table('calificacion',
    sa.Column('id_calificacion', sa.Integer(), nullable=False),
    sa.Column('calificacion', sa.Float(), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('cve_usuario_calificado', sa.Integer(), nullable=True),
    sa.Column('cve_usuario_calificador', sa.Integer(), nullable=True),
    sa.Column('cve_subasta', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cve_subasta'], ['subasta.id_subasta'], ),
    sa.ForeignKeyConstraint(['cve_usuario_calificado'], ['usuario.id_usuario'], ),
    sa.ForeignKeyConstraint(['cve_usuario_calificador'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_calificacion')
    )
    op.create_index(op.f('ix_calificacion_id_calificacion'), 'calificacion', ['id_calificacion'], unique=False)
    op.create_table('confirmacion_entrega',
    sa.Column('id_confirmacion', sa.Integer(), nullable=False),
    sa.Column('url_imagen_envio', sa.String(length=500), nullable=True),
    sa.Column('url_imagen_recepcion', sa.String(length=500), nullable=True),
    sa.Column('fecha_envio_confirmada', sa.DateTime(), nullable=True),
    sa.Column('fecha_recepcion_confirmada', sa.DateTime(), nullable=True),
    sa.Column('cve_subasta', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cve_subasta'], ['subasta.id_subasta'], ),
    sa.PrimaryKeyConstraint('id_confirmacion'),
    sa.UniqueConstraint('cve_subasta')
    )
    op.create_index(op.f('ix_confirmacion_entrega_id_confirmacion'), 'confirmacion_entrega', ['id_confirmacion'], unique=False)
    op.create_table('oferta',
    sa.Column('id_oferta', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('cve_usuario', sa.Integer(), nullable=True),
    sa.Column('cve_subasta', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cve_subasta'], ['subasta.id_subasta'], ),
    sa.ForeignKeyConstraint(['cve_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_oferta')
    )
    op.create_index(op.f('ix_oferta_id_oferta'), 'oferta', ['id_oferta'], unique=False)
    op.create_table('pago',
    sa.Column('id_pago', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('fecha_realizacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_limite', sa.DateTime(), nullable=False),
    sa.Column('url_comprobante', sa.String(length=500), nullable=True),
    sa.Column('metodo_pago', sa.String(length=50), nullable=True),
    sa.Column('es_escalonado', sa.Boolean(), nullable=True),
    sa.Column('tipo_pago_escalonado', sa.String(length=100), nullable=True),
    sa.Column('cve_status', sa.Integer(), nullable=True),
    sa.Column('cve_subasta', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cve_status'], ['status_pago.id_status'], ),
    sa.ForeignKeyConstraint(['cve_subasta'], ['subasta.id_subasta'], ),
    sa.PrimaryKeyConstraint('id_pago')
    )
    op.create_index(op.f('ix_pago_id_pago'), 'pago', ['id_pago'], unique=False)
    op.create_table('notificacion',
    sa.Column('id_notificacion', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('fecha_envio', sa.DateTime(), nullable=True),
    sa.Column('leida', sa.Boolean(), nullable=True),
    sa.Column('cve_usuario', sa.Integer(), nullable=True),
    sa.Column('cve_tipo_notificacion', sa.Integer(), nullable=True),
    sa.Column('cve_oferta', sa.Integer(), nullable=True),
    sa.Column('cve_subasta', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cve_oferta'], ['oferta.id_oferta'], ),
    sa.ForeignKeyConstraint(['cve_subasta'], ['subasta.id_subasta'], ),
    sa.ForeignKeyConstraint(['cve_tipo_notificacion'], ['tipo_notificacion.id_tipo_notificacion'], ),
    sa.ForeignKeyConstraint(['cve_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_notificacion')
    )
    op.create_index(op.f('ix_notificacion_id_notificacion'), 'notificacion', ['id_notificacion'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notificacion_id_notificacion'), table_name='notificacion')
    op.drop_table('notificacion')
    op.drop_index(op.f('ix_pago_id_pago'), table_name='pago')
    op.drop_table('pago')
    op.drop_index(op.f('ix_oferta_id_oferta'), table_name='oferta')
    op.drop_table('oferta')
    op.drop_index(op.f('ix_confirmacion_entrega_id_confirmacion'), table_name='confirmacion_entrega')
    op.drop_table('confirmacion_entrega')
    op.drop_index(op.f('ix_calificacion_id_calificacion'), table_name='calificacion')
    op.drop_table('calificacion')
    op.drop_index(op.f('ix_vehiculo_id_vehiculo'), table_name='vehiculo')
    op.drop_table('vehiculo')
    op.drop_index(op.f('ix_subasta_id_subasta'), table_name='subasta')
    op.drop_table('subasta')
    op.drop_index(op.f('ix_inmueble_id_inmueble'), table_name='inmueble')
    op.drop_table('inmueble')
    op.drop_index(op.f('ix_foto_producto_id_foto'), table_name='foto_producto')
    op.drop_table('foto_producto')
    op.drop_index(op.f('ix_producto_id_producto'), table_name='producto')
    op.drop_table('producto')
    op.drop_index(op.f('ix_metodo_envio_id_metodo_envio'), table_name='metodo_envio')
    op.drop_table('metodo_envio')
    op.drop_index(op.f('ix_usuario_id_usuario'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_correo'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_index(op.f('ix_tipo_usuario_id_tipo_usuario'), table_name='tipo_usuario')
    op.drop_table('tipo_usuario')
    op.drop_index(op.f('ix_tipo_subasta_id_tipo_subasta'), table_name='tipo_subasta')
    op.drop_table('tipo_subasta')
    op.drop_index(op.f('ix_tipo_notificacion_id_tipo_notificacion'), table_name='tipo_notificacion')
    op.drop_table('tipo_notificacion')
    op.drop_index(op.f('ix_status_subasta_id_status'), table_name='status_subasta')
    op.drop_table('status_subasta')
    op.drop_index(op.f('ix_status_producto_id_status'), table_name='status_producto')
    op.drop_table('status_producto')
    op.drop_index(op.f('ix_status_pago_id_status'), table_name='status_pago')
    op.drop_table('status_pago')
    op.drop_index(op.f('ix_condicion_id_condicion'), table_name='condicion')
    op.drop_table('condicion')
    op.drop_index(op.f('ix_categoria_id_categoria'), table_name='categoria')
    op.drop_table('categoria')
    # ### end Alembic commands ###
